'use client';

import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Lang = 'id' | 'en';

interface LanguageState {
  lang: Lang;
  setLang: (lang: Lang) => void;
}

export const useLanguage = create<LanguageState>()(
  persist(
    (set) => ({
      lang: 'id',
      setLang: (lang) => set({ lang }),
    }),
    { name: 'kawabel-lang' }
  )
);

// Translation strings
const translations: Record<Lang, Record<string, string>> = {
  id: {
    // Home
    greeting: 'Halo',
    whatToStudy: 'Mau belajar apa hari ini?',
    continueStudying: 'Lanjut Belajar',
    learnUnlimited: 'Belajar tanpa batas',
    upgradePremium: 'Upgrade Premium — gratis 7 hari',
    shareToParent: 'Bagikan ke Orang Tua',
    parentCanSee: 'Orang tua bisa lihat progress belajarmu di',
    sendCodeToParent: 'Kirim kode ini ke orang tua agar bisa melihat progressmu',
    signInForOnline: 'Masuk dengan Google agar orang tua bisa pantau online dari HP mereka',
    copy: 'Salin',
    copied: 'Tersalin!',
    achievements: 'Pencapaian',
    days: 'hari',

    // Features
    askHomework: 'Tanya PR',
    askHomeworkDesc: 'Ketik pertanyaan, langsung dijawab',
    photoQuestion: 'Foto Soal',
    photoQuestionDesc: 'Untuk mendapatkan penjelasan',
    dictation: 'Dikte',
    dictationDesc: 'Foto daftar kata, dengarkan & tulis',
    examPractice: 'Latihan Ujian',
    examPracticeDesc: 'Foto buku atau pilih topik, langsung buat kuis',

    // Nav
    home: 'Beranda',
    ask: 'Tanya',
    dict: 'Dikte',
    exam: 'Ujian',
    champion: 'Juara',

    // New user
    yourAIFriend: 'Kawan Belajar AI-mu',
    heroSubtitle: 'Tanya PR, foto soal, latihan ujian, dan dikte — semua dibantu AI, kapan saja.',
    startAskNow: 'Mulai Tanya Sekarang',
    whatCanHelp: 'Apa yang bisa Kawabel bantu?',
    howToUse: 'Cara pakai',
    step1: 'Pilih fitur di atas atau langsung ketik pertanyaan',
    step2: 'Kawabel jelaskan jawaban langkah demi langkah',
    step3: 'Kumpulkan XP dan naik level sambil belajar!',

    // Onboarding
    whatsYourName: 'Halo! Siapa namamu?',
    imKawabel: 'Aku Kawabel, kawan belajarmu!',
    typeName: 'Ketik namamu...',
    next: 'Lanjut',
    whatGrade: 'Kelas berapa,',
    soKawabelCanHelp: 'Biar Kawabel bisa bantu sesuai pelajaranmu',
    back: 'Kembali',
    startLearning: 'Mulai Belajar!',

    // Footer
    parent: 'Orang Tua',
    privacy: 'Privasi',
    terms: 'Ketentuan',

    // Chat page
    chatEmpty: 'Ada PR atau soal yang susah?',
    chatEmptyDesc: 'Ketik pertanyaan atau foto soalmu — aku bantu jelaskan langkah demi langkah!',
    chatSuggestion1: 'Bantu PR Matematika',
    chatSuggestion2: 'Jelaskan fotosintesis',
    chatSuggestion3: 'Latihan soal',
    chatDelete: 'Hapus',
    chatListening: 'Mendengarkan...',
    chatPlaceholder: 'Ketik pertanyaanmu...',

    // Dictation page
    dictTitle: 'Dikte',
    dictSubtitle: 'Foto → Dengarkan → Tulis → Periksa',
    dictPhotoWords: 'Foto Daftar Kata',
    dictPhotoWordsDesc: 'Foto halaman buku yang berisi kata-kata yang ingin di diktekan',
    dictSupports: 'Mendukung: Mandarin, Arab, Inggris, Indonesia, dan bahasa lainnya',
    dictHowTo: 'Cara pakai:',
    dictStep1: 'Siapkan halaman daftar kata yang ingin di diktekan',
    dictStep2: 'Foto daftar kata tersebut — pastikan semua karakter terlihat jelas',
    dictStep3Prefix: '',
    dictStep3Suffix: 'akan membacakan kata satu per satu, kamu tulis di kertas',
    dictStep4: 'Setelah selesai, foto hasil tulisanmu untuk diperiksa',
    dictGallery: 'Atau pilih foto dari galeri',
    dictReading: 'Membaca kata dari foto...',
    dictReadingDesc: 'sedang mengenali kata-kata dari foto',
    dictWord: 'Kata',
    dictOf: 'dari',
    dictListened: 'didengarkan',
    dictPrepare: 'Siapkan kertas & pensil!',
    dictPrepareDesc: 'Tekan tombol untuk mendengar kata, lalu tulis jawabanmu di kertas. Setiap kata bisa didengar berkali-kali.',
    dictMeaning: 'Arti',
    dictListen: 'Dengarkan',
    dictPlayed: 'Sudah diputar — tulis di kertas, lalu lanjut!',
    dictRepeat: 'Ulang',
    dictNext: 'Lanjut',
    dictFinish: 'Selesai Dikte',
    dictWordList: 'Daftar kata:',
    dictPhotoAnswer: 'Langkah 3: Foto Jawabanmu',
    dictPhotoAnswerDesc: 'Foto kertas yang berisi tulisanmu. Pastikan tulisan terlihat jelas!',
    dictPhotoTips: 'Tips foto yang bagus:',
    dictTip1: 'Letakkan kertas di permukaan datar dengan cahaya terang',
    dictTip2: 'Pastikan semua tulisan masuk dalam frame',
    dictTip3: 'Tulis dengan urutan yang sama seperti dikte',
    dictTip4: 'Hindari bayangan di atas tulisan',
    dictPhotoBtn: 'Foto Jawaban',
    dictBackToDictation: '\u2190 Kembali ke dikte',
    dictChecking: 'Memeriksa jawaban...',
    dictCheckingDesc: 'sedang membandingkan tulisanmu',
    dictCorrect: 'Benar',
    dictPerfect: 'Sempurna! Kamu hebat!',
    dictGood: 'Bagus sekali! Terus berlatih!',
    dictTryAgain: 'Jangan menyerah, coba lagi!',
    dictStartOver: 'Mulai Baru',
    dictRepeatSame: 'Ulangi Kata Sama',
    dictClose: 'Tutup',

    // Test prep page
    testTitle: 'Latihan Ujian',
    testSchoolType: 'Pilih jenis sekolah',
    testSubject: 'Pilih mata pelajaran',
    testTopicDesc: 'foto buku atau pilih topik',
    testChangeSchool: 'Ganti jenis sekolah',
    testChangeSubject: 'Ganti mata pelajaran',
    testPhotoBook: 'Foto halaman buku',
    testPhotoBookDesc: 'Foto halaman buku pelajaran — soal akan dibuat berdasarkan isi buku',
    testAdd: 'Tambah',
    testPagesPhotoed: 'halaman difoto — tambah lagi atau buat soal',
    testGenFromPages: 'Buat Soal dari',
    testPages: 'Halaman',
    testPhotoPageBtn: 'Foto Halaman Buku',
    testPhotoMultiple: 'Foto beberapa halaman, lalu buat soal',
    testOrTypeTopic: 'atau ketik topik',
    testTopicExample: 'Contoh',
    testStartPractice: 'Mulai Latihan',
    testRandomPractice: 'Latihan Acak',
    testReadingPages: 'Membaca',
    testPreparingQuiz: 'Menyiapkan soal',
    testTopic: 'Topik',
    testQuestion: 'Soal',
    testExplanation: 'Penjelasan',
    testNextQuestion: 'Soal Berikutnya',
    testViewResults: 'Lihat Hasil',
    testHeartsEmpty: 'Hati habis! Tunggu regenerasi atau isi ulang dengan gems.',
    testPerfect: 'Luar biasa! Kamu sempurna!',
    testGreat: 'Keren banget!',
    testKeepGoing: 'Bagus, terus berlatih!',
    testDontGiveUp: 'Jangan menyerah, coba lagi!',
    testPerfectBonus: 'Sempurna! +20 XP bonus',
    testChangeMapel: 'Ganti Mapel',
    testTryAgain: 'Coba Lagi',
    testCombo: 'kombo',

    // Leaderboard page
    lbTitle: 'Papan Juara',
    lbSubtitle: 'Siapa paling rajin belajar?',
    lbWeek: 'Minggu Ini',
    lbMonth: 'Bulan Ini',
    lbAll: 'Semua',
    lbNoData: 'Belum ada data',
    lbYou: 'kamu',
    lbFriends: 'Teman',

    // Progress page
    progTitle: 'Progress Belajar',
    progSubtitle: 'Perkembangan belajar',
    progSignIn: 'Masuk untuk melihat progress belajarmu',
    progSignInTitle: 'Masuk untuk melihat progress',
    progSignInDesc: 'Dengan masuk menggunakan Google, semua hasil belajar, skor, dan pencapaianmu akan tersimpan dan bisa dilihat di sini.',
    progWithout: 'Tanpa masuk, kamu tetap bisa belajar — tapi progress tidak tersimpan ke server.',
    progHomework: 'PR',
    progExam: 'Ujian',
    progDictation: 'Dikte',
    progRecent: 'Aktivitas Terakhir',
    progNoActivity: 'Belum ada aktivitas. Mulai belajar!',

    // Pricing page
    priceTitle: 'Belajar Tanpa Batas',
    priceSubtitle: 'Investasi terbaik untuk masa depan anak',
    priceFree: 'Gratis',
    priceMonth: 'bulan',
    priceFreeDesc: 'Akses dasar dengan batasan harian',
    pricePremium: 'Premium',
    pricePerStudent: 'per siswa',
    priceActive: 'Aktif',
    priceFullAccess: 'Akses penuh tanpa batas',
    priceSubscribe: 'Langganan',
    priceTrialDays: 'hari tersisa',
    priceActiveSub: 'Langganan aktif',
    priceFreeTrial: '+ gratis 7 hari pertama!',
    priceSocial: 'Lebih hemat dari les privat (Rp 1-2jt/bulan). Kawabel siap bantu 24/7 kapan saja.',
    priceVoucher: 'Punya voucher?',
    priceVoucherDesc: 'Masukkan kode untuk aktivasi Premium gratis',
    priceVoucherUse: 'Pakai',
    pricePartner: 'Punya bimbel atau sekolah?',
    pricePartnerDesc: 'Daftar sebagai Partner — harga spesial per siswa',
    priceFAQ: 'Pertanyaan Umum',
    pricePerDay: 'hari',

    // Pricing FAQ
    priceFaqQ1: 'Apakah ada masa percobaan gratis?',
    priceFaqA1: 'Ya! Semua pengguna baru mendapat 7 hari akses penuh gratis. Tidak perlu kartu kredit.',
    priceFaqQ2: 'Bagaimana cara bayar?',
    priceFaqA2: 'Pembayaran melalui transfer bank BCA. Setelah transfer, upload bukti pembayaran dan tim kami akan verifikasi dalam 1x24 jam.',
    priceFaqQ3: 'Berapa biaya langganan?',
    priceFaqA3: 'Langganan Premium Rp 750.000/bulan per siswa. Kamu juga mendapat 7 hari gratis untuk mencoba semua fitur tanpa risiko.',
    priceFaqQ4: 'Apa yang terjadi setelah masa percobaan?',
    priceFaqA4: 'Kamu tetap bisa menggunakan Kawabel dengan batasan harian (5 chat, 2 foto PR, 2 kuis, 3 dikte per hari). Upgrade kapan saja untuk akses unlimited.',
    priceFaqQ5: 'Bisa berhenti berlangganan?',
    priceFaqA5: 'Tentu! Langganan tidak diperpanjang otomatis. Setelah masa aktif berakhir, kamu kembali ke paket gratis.',
    priceFaqQ6: 'Saya punya bimbel, bisa kerja sama?',
    priceFaqA6: 'Bisa! Kami punya program khusus untuk bimbel dan sekolah dengan harga spesial per siswa. Kunjungi halaman Partner kami untuk info lebih lanjut.',
    priceFaqQ7: 'Apa itu Laporan WhatsApp?',
    priceFaqA7: 'Orang tua akan menerima laporan mingguan di WhatsApp tentang progress belajar anak, termasuk mata pelajaran yang dipelajari dan pencapaian.',

    // Pricing comparison labels
    featureChat: 'Chat AI',
    featurePhoto: 'Foto PR',
    featureQuiz: 'Kuis Latihan',
    featureDictation: 'Dikte',
    featureHearts: 'Hati (nyawa)',
    featureNoAds: 'Tanpa iklan',
    featureWhatsApp: 'Laporan WhatsApp',
    featureCurriculum: 'Kurikulum lengkap',

    // Upgrade prompt
    upgradeLimitReached: 'Batas harian tercapai!',
    upgradeUsed: 'hari ini sudah digunakan',
    upgradeUsedCount: 'terpakai',
    upgradeCTA: 'Upgrade ke Premium',
    upgradeOrWait: 'Atau tunggu besok',
    upgradeTrialHint: 'Gratis 7 hari!',

    // Friends section
    friendsTitle: 'Teman Belajar',
    friendsAdd: '+ Tambah Teman',
    friendsClose: 'Tutup',
    friendsCodeHint: 'Masukkan kode teman (contoh: BUDI-1234)',
    friendsAddBtn: 'Tambah',
    friendsEmpty: 'Belum ada teman. Tambah teman untuk belajar bareng!',
    friendsNudge: 'Ajak',

    // Parent page
    parentTitle: 'Lihat Progress Anak',
    parentDesc: 'Masukkan kode dari anak Anda untuk melihat progress belajarnya',
    parentPlaceholder: 'Masukkan kode (contoh: BUDI-1234)',
    parentSearch: 'Lihat Progress',
    parentSearching: 'Mencari...',
    parentHow: 'Bagaimana cara mendapatkan kode?',
    parentHowDesc: 'Anak Anda bisa menemukan kode ini di halaman utama Kawabel setelah masuk dengan Google. Kode berupa kombinasi nama + angka unik.',
    parentStars: 'Bintang',
    parentSessions: 'Sesi Belajar',
    parentAvg: 'Rata-rata',
    parentHistory: 'Riwayat Belajar',
    parentNoHistory: 'Belum ada riwayat belajar. Anak Anda baru mulai menggunakan Kawabel.',
    parentSearchOther: 'Cari Anak Lain',
    parentLabel: 'Orang Tua',

    // Common
    unlimited: 'Unlimited',
    correct: 'Benar',
  },
  en: {
    // Home
    greeting: 'Hello',
    whatToStudy: 'What do you want to study today?',
    continueStudying: 'Continue Studying',
    learnUnlimited: 'Learn without limits',
    upgradePremium: 'Upgrade to Premium — free 7-day trial',
    shareToParent: 'Share with Parents',
    parentCanSee: 'Parents can see your progress at',
    sendCodeToParent: 'Send this code to your parents so they can view your progress',
    signInForOnline: 'Sign in with Google so parents can track online from their phone',
    copy: 'Copy',
    copied: 'Copied!',
    achievements: 'Achievements',
    days: 'days',

    // Features
    askHomework: 'Ask Homework',
    askHomeworkDesc: 'Type a question, get answers instantly',
    photoQuestion: 'Photo Question',
    photoQuestionDesc: 'Take a photo for explanations',
    dictation: 'Dictation',
    dictationDesc: 'Photo word list, listen & write',
    examPractice: 'Exam Practice',
    examPracticeDesc: 'Photo textbook or pick a topic, instant quiz',

    // Nav
    home: 'Home',
    ask: 'Ask',
    dict: 'Dictation',
    exam: 'Exam',
    champion: 'Rank',

    // New user
    yourAIFriend: 'Your AI Study Buddy',
    heroSubtitle: 'Ask homework, photo questions, exam practice, and dictation — all powered by AI, anytime.',
    startAskNow: 'Start Asking Now',
    whatCanHelp: 'What can Kawabel help with?',
    howToUse: 'How it works',
    step1: 'Pick a feature above or just type your question',
    step2: 'Kawabel explains the answer step by step',
    step3: 'Collect XP and level up while studying!',

    // Onboarding
    whatsYourName: 'Hi! What\'s your name?',
    imKawabel: 'I\'m Kawabel, your study buddy!',
    typeName: 'Type your name...',
    next: 'Next',
    whatGrade: 'What grade,',
    soKawabelCanHelp: 'So Kawabel can help with your subjects',
    back: 'Back',
    startLearning: 'Start Learning!',

    // Footer
    parent: 'Parents',
    privacy: 'Privacy',
    terms: 'Terms',

    // Chat page
    chatEmpty: 'Having trouble with homework?',
    chatEmptyDesc: 'Type a question or take a photo — I\'ll explain step by step!',
    chatSuggestion1: 'Help with Math homework',
    chatSuggestion2: 'Explain photosynthesis',
    chatSuggestion3: 'Practice questions',
    chatDelete: 'Clear',
    chatListening: 'Listening...',
    chatPlaceholder: 'Type your question...',

    // Dictation page
    dictTitle: 'Dictation',
    dictSubtitle: 'Photo \u2192 Listen \u2192 Write \u2192 Check',
    dictPhotoWords: 'Photo Word List',
    dictPhotoWordsDesc: 'Take a photo of the page with words to be dictated',
    dictSupports: 'Supports: Mandarin, Arabic, English, Indonesian, and more',
    dictHowTo: 'How to use:',
    dictStep1: 'Prepare the page with words to be dictated',
    dictStep2: 'Take a photo \u2014 make sure all characters are clearly visible',
    dictStep3Prefix: '',
    dictStep3Suffix: 'will read words one by one, write them on paper',
    dictStep4: 'When done, take a photo of your writing to check',
    dictGallery: 'Or pick a photo from gallery',
    dictReading: 'Reading words from photo...',
    dictReadingDesc: 'is recognizing words from the photo',
    dictWord: 'Word',
    dictOf: 'of',
    dictListened: 'listened',
    dictPrepare: 'Get your paper & pencil ready!',
    dictPrepareDesc: 'Press the button to hear the word, then write your answer on paper. Each word can be replayed.',
    dictMeaning: 'Meaning',
    dictListen: 'Listen',
    dictPlayed: 'Already played \u2014 write it down, then continue!',
    dictRepeat: 'Repeat',
    dictNext: 'Next',
    dictFinish: 'Finish Dictation',
    dictWordList: 'Word list:',
    dictPhotoAnswer: 'Step 3: Photo Your Answers',
    dictPhotoAnswerDesc: 'Take a photo of your written answers. Make sure the writing is clear!',
    dictPhotoTips: 'Tips for a good photo:',
    dictTip1: 'Place paper on a flat surface with bright light',
    dictTip2: 'Make sure all writing is in the frame',
    dictTip3: 'Write in the same order as the dictation',
    dictTip4: 'Avoid shadows on the writing',
    dictPhotoBtn: 'Photo Answers',
    dictBackToDictation: '\u2190 Back to dictation',
    dictChecking: 'Checking answers...',
    dictCheckingDesc: 'is comparing your writing',
    dictCorrect: 'Correct',
    dictPerfect: 'Perfect! You\'re amazing!',
    dictGood: 'Great job! Keep practicing!',
    dictTryAgain: 'Don\'t give up, try again!',
    dictStartOver: 'Start Over',
    dictRepeatSame: 'Repeat Same Words',
    dictClose: 'Close',

    // Test prep page
    testTitle: 'Exam Practice',
    testSchoolType: 'Choose school type',
    testSubject: 'Choose a subject',
    testTopicDesc: 'photo textbook or pick a topic',
    testChangeSchool: 'Change school type',
    testChangeSubject: 'Change subject',
    testPhotoBook: 'Photo textbook page',
    testPhotoBookDesc: 'Photo a textbook page \u2014 questions will be based on the content',
    testAdd: 'Add',
    testPagesPhotoed: 'pages captured \u2014 add more or generate quiz',
    testGenFromPages: 'Generate Quiz from',
    testPages: 'Pages',
    testPhotoPageBtn: 'Photo Textbook Page',
    testPhotoMultiple: 'Photo multiple pages, then generate quiz',
    testOrTypeTopic: 'or type a topic',
    testTopicExample: 'Example',
    testStartPractice: 'Start Practice',
    testRandomPractice: 'Random Practice',
    testReadingPages: 'Reading',
    testPreparingQuiz: 'Preparing questions',
    testTopic: 'Topic',
    testQuestion: 'Question',
    testExplanation: 'Explanation',
    testNextQuestion: 'Next Question',
    testViewResults: 'View Results',
    testHeartsEmpty: 'No hearts left! Wait to regenerate or refill with gems.',
    testPerfect: 'Amazing! You got a perfect score!',
    testGreat: 'Awesome!',
    testKeepGoing: 'Good, keep practicing!',
    testDontGiveUp: 'Don\'t give up, try again!',
    testPerfectBonus: 'Perfect! +20 XP bonus',
    testChangeMapel: 'Change Subject',
    testTryAgain: 'Try Again',
    testCombo: 'combo',

    // Leaderboard page
    lbTitle: 'Leaderboard',
    lbSubtitle: 'Who studies the hardest?',
    lbWeek: 'This Week',
    lbMonth: 'This Month',
    lbAll: 'All Time',
    lbNoData: 'No data yet',
    lbYou: 'you',
    lbFriends: 'Friends',

    // Progress page
    progTitle: 'Study Progress',
    progSubtitle: 'Learning progress for',
    progSignIn: 'Sign in to see your study progress',
    progSignInTitle: 'Sign in to see progress',
    progSignInDesc: 'By signing in with Google, all your study results, scores, and achievements will be saved and visible here.',
    progWithout: 'Without signing in, you can still study \u2014 but progress won\'t sync to server.',
    progHomework: 'Homework',
    progExam: 'Exam',
    progDictation: 'Dictation',
    progRecent: 'Recent Activity',
    progNoActivity: 'No activity yet. Start studying!',

    // Pricing page
    priceTitle: 'Learn Without Limits',
    priceSubtitle: 'The best investment for your child\'s future',
    priceFree: 'Free',
    priceMonth: 'month',
    priceFreeDesc: 'Basic access with daily limits',
    pricePremium: 'Premium',
    pricePerStudent: 'per student',
    priceActive: 'Active',
    priceFullAccess: 'Full unlimited access',
    priceSubscribe: 'Subscribe',
    priceTrialDays: 'days remaining',
    priceActiveSub: 'Active subscription',
    priceFreeTrial: '+ free 7-day trial!',
    priceSocial: 'More affordable than private tutoring (Rp 1-2M/month). Kawabel is ready to help 24/7.',
    priceVoucher: 'Have a voucher?',
    priceVoucherDesc: 'Enter code to activate free Premium',
    priceVoucherUse: 'Apply',
    pricePartner: 'Own a tutoring center or school?',
    pricePartnerDesc: 'Register as a Partner \u2014 special pricing per student',
    priceFAQ: 'FAQ',
    pricePerDay: 'day',

    // Pricing FAQ
    priceFaqQ1: 'Is there a free trial?',
    priceFaqA1: 'Yes! All new users get 7 days of full access for free. No credit card required.',
    priceFaqQ2: 'How do I pay?',
    priceFaqA2: 'Payment is via BCA bank transfer. After transferring, upload proof of payment and our team will verify within 24 hours.',
    priceFaqQ3: 'How much does the subscription cost?',
    priceFaqA3: 'Premium subscription is Rp 750,000/month per student. You also get 7 free days to try all features risk-free.',
    priceFaqQ4: 'What happens after the trial ends?',
    priceFaqA4: 'You can still use Kawabel with daily limits (5 chats, 2 photo questions, 2 quizzes, 3 dictations per day). Upgrade anytime for unlimited access.',
    priceFaqQ5: 'Can I cancel my subscription?',
    priceFaqA5: 'Of course! Subscriptions do not auto-renew. After your active period ends, you return to the free plan.',
    priceFaqQ6: 'I run a tutoring center, can we partner?',
    priceFaqA6: 'Yes! We have special programs for tutoring centers and schools with special per-student pricing. Visit our Partner page for more info.',
    priceFaqQ7: 'What are WhatsApp Reports?',
    priceFaqA7: 'Parents will receive weekly reports on WhatsApp about their child\'s study progress, including subjects studied and achievements.',

    // Pricing comparison labels
    featureChat: 'AI Chat',
    featurePhoto: 'Photo Homework',
    featureQuiz: 'Practice Quiz',
    featureDictation: 'Dictation',
    featureHearts: 'Hearts (lives)',
    featureNoAds: 'No ads',
    featureWhatsApp: 'WhatsApp Reports',
    featureCurriculum: 'Full curriculum',

    // Upgrade prompt
    upgradeLimitReached: 'Daily limit reached!',
    upgradeUsed: 'used today',
    upgradeUsedCount: 'used',
    upgradeCTA: 'Upgrade to Premium',
    upgradeOrWait: 'Or wait until tomorrow',
    upgradeTrialHint: 'Free 7-day trial!',

    // Friends section
    friendsTitle: 'Study Friends',
    friendsAdd: '+ Add Friend',
    friendsClose: 'Close',
    friendsCodeHint: 'Enter friend code (e.g. BUDI-1234)',
    friendsAddBtn: 'Add',
    friendsEmpty: 'No friends yet. Add friends to study together!',
    friendsNudge: 'Invite',

    // Parent page
    parentTitle: 'View Child\'s Progress',
    parentDesc: 'Enter your child\'s code to view their study progress',
    parentPlaceholder: 'Enter code (e.g. BUDI-1234)',
    parentSearch: 'View Progress',
    parentSearching: 'Searching...',
    parentHow: 'How to get the code?',
    parentHowDesc: 'Your child can find this code on the Kawabel home page after signing in with Google. The code is a name + unique number combination.',
    parentStars: 'Stars',
    parentSessions: 'Study Sessions',
    parentAvg: 'Average',
    parentHistory: 'Study History',
    parentNoHistory: 'No study history yet. Your child just started using Kawabel.',
    parentSearchOther: 'Search Another Child',
    parentLabel: 'Parents',

    // Common
    unlimited: 'Unlimited',
    correct: 'Correct',
  },
};

export type TranslationKey = keyof typeof translations.id;

export function useT() {
  const { lang } = useLanguage();
  return (key: TranslationKey) => translations[lang][key] || translations.id[key];
}
